### ISSUE TITLE
Twice as many fragment gradient calculations as necessary

### ISSUE THREAD

**Issue by hokru** [qrefine/qrefine#32]
**Describe the bug**
Because of this https://github.com/qrefine/qrefine/blob/master/cluster_restraints.py#L59  we calculated clustered gradients once in serial and once again with parallel_map. There used to be a `if(0)` to suppress the gradient, probably was removed during debugging and forgotten?

**Desktop (please complete the following information):**
 - OS: Debian Linux
 - Version current master 3cff895155b8ebacbf2665500185b47ad379e804 | phenix-dev-3385

**Comment by biczysko** [comment]
That bug is also related to the problems with sending parallel jobs to the gpu nodes.  Serial would not work with queueing system, only parallel function can handle that. We were only able to run correctly on gpu with part  https://github.com/qrefine/qrefine/blob/master/cluster_restraints.py#L49-#L65 removed

**Comment by hokru** [comment]
@pafonine Could you please have look?
Mark traced changes back to this commit: https://github.com/qrefine/qrefine/commit/978f67ea41d0c65ae01f0d441218a8e16b92d945

**Comment by pafonine** [comment]
This was meant to be a debugging exercise. Also, as you can see this is 
just a loop over fragments where we do a single gradient calculation for 
each fragment, and also write a PDB file with each fragment just before 
doing that. The hope was to be able to catch bad fragments (those that 
crash QM engines). Clearly this is a wasteful approach and should not be 
there (at least by default!). I've just commented it out.

Apart from wasting runtime, how this was problematic otherwise (this is 
something that wasn't clear to me from the conversation)?

Pavel

**Comment by biczysko** [comment]
Hi,
that has created problems with gpu computations.
Moreover, commented out (as we were doing in order to run gpu/Terachem jobs) with recent versions of phenix (dev-3385 more precisely) was leading to crashing as below

cheers

goska

--
I 
Unexpected response from LSF: ''
Traceback (most recent call last):
  File "/public/phenix/phenix-dev-3385/build/../modules/qrefine/command_line/refine.py", line 144, in <module>
    run(args=sys.argv[1:], log=log)
  File "/public/phenix/phenix-dev-3385/build/../modules/qrefine/command_line/refine.py", line 138, in run
    log      = log)
  File "/public/phenix/phenix-dev-3385/modules/qrefine/qr.py", line 627, in run
    results               = results_manager)
  File "/public/phenix/phenix-dev-3385/modules/qrefine/driver.py", line 470, in refine
    calculator.calculate_weight(verbose=params.debug)
  File "/public/phenix/phenix-dev-3385/modules/qrefine/calculator.py", line 200, in calculate_weight
    verbose = verbose)
  File "/public/phenix/phenix-dev-3385/modules/qrefine/calculator.py", line 95, in compute_weight
    tc, gc = rm.target_and_gradients(sites_cart=xrs.sites_cart())
  File "/public/phenix/phenix-dev-3385/modules/qrefine/cluster_restraints.py", line 96, in target_and_gradients
    raise Sorry('process finished with error: %s' % e)
Sorry: process finished with error: Unexpected response from LSF: ''


in 2019-02-06 06:49:19,"Pavel Afonine" <notifications@github.com> Compose:

**Comment by mpwaller** [comment]
@pafonine Running the jobs in serial causes a crash because they are run on the head node which does not have a GPU attached. If we use parallel_map then it uses the queueing system, which submits jobs to the nodes which each have GPUs installed.  The debug code was just running in serial, which lead to the problem. When we use Terachem we always use parallel mode, if we are debugging in serial, then we would have to use a machine which has a GPU attached.  We should think about adding some method to check if a GPU is installed and throw a useful exception for the user. The stacktrace currently thrown is too cryptic.

**Comment by pafonine** [comment]
OK, clear now. As I said I commented out that code so it should fix the 
issue.
Pavel

**Comment by biczysko** [comment]
see my email please
goska


in 2019-02-06 09:08:27,"Pavel Afonine" <notifications@github.com> Compose:

**Comment by hokru** [comment]
closed by https://github.com/qrefine/qrefine/commit/a91cf37d8d8f3d0e03aec1c344ed89b6172ed931

**Comment by nwmoriarty** [comment]
Goska

I believe the LSF error is queue related and we need more information about
what is happening. The code writes input files for the queue and makes a
command call. If this is not working, it will crash. Maybe the input file
or the call is wrong but this needs to be checked carefully.

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov
